name: "CI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Integration Test
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: dotnet test
