name: "CI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Integration Test
  tests:
    name: "Integration Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Tests
        run: dotnet test
